### ISSUE TITLE
Support for Astro @ 4.0?

### ISSUE THREAD

**Issue by joshgillies** [denoland/deno-astro-adapter#10]
There's been a recent major release of Astro https://astro.build/blog/astro-4/, and from the looks of things this adapter should work, however the peerDependency expects `astro@^3.0.13` https://github.com/denoland/deno-astro-adapter/blob/main/package.json#L37.

**Comment by jueewo** [comment]
I'm having issues updating to Astro 4 as well, error message:
```
Could not resolve '#async_hooks' from 'file:///.../node_modules/.deno/astro@4.0.4/node_modules/p-limit/index.js'.
```

**Comment by jose-donato** [comment]
+1

**Comment by Astisme** [comment]
+1

**Comment by jamesli2021** [comment]
Need fix for Astro 4.3.2 and beyond.

**Comment by aaronlifton** [comment]
Need a fix as well. Was hoping to deploy my astro site on deno deploy.

**Comment by lajbel** [comment]
+1

**Comment by fro-profesional** [comment]
I saw on discord, that currently the node build with unstable flags is working in deno

https://discord.com/channels/684898665143206084/1204542187199668235/1204547434324426792

**Comment by toybreaker** [comment]
ok, but what is the point of using deno if then i have to enable node unstable flag… nope, not yet possible to consider using it atm… and its a pity, cos Asdtro is in the stack Deno is a maybe soon at this point, and i am sure i am not the only one

**Comment by treb0r** [comment]
Is this adapter no longer maintained?

**Comment by jueewo** [comment]
Astro is great 🚀🚀, but I gave up waiting for an update here. I assume it's not maintained anymore, Deno is even not mentioned on the Astro website (as far as I know this adapter was originally maintained by Astro, it seems it was took over by Deno and the development stopped).

**Comment by skrzepij** [comment]
It looks like the problem has been solved, but an update to the npm registry has not yet been released. 
Temporarily, you can update package.json and install the adapter directly from the github repository - it helped in my case.

```json
  "dependencies": {
    "@astrojs/deno": "github:denoland/deno-astro-adapter",
    "astro": "^4.5.9"
  }
```

So maybe the adapter will still be developed. Finger crossed 🤞🏻

**Comment by kt3k** [comment]
We changed the package name from `@astrojs/deno` to `@deno/astro-adapter` because of the change of the maintainers.

Now the latest version (v0.1.2) of `@deno/astro-adapter` should support astro 4.0.

**Comment by khoipro** [comment]
Please also update related document. https://docs.astro.build/en/guides/deploy/deno/

**Comment by EdamAme-x** [comment]
nice works bro!!!

**Comment by EdamAme-x** [comment]
hmm...
Errors no longer occur, but process.env is not loaded

**Comment by EdamAme-x** [comment]
my deps

```json
{
  "name": "tmp",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "deno run -A npm:astro dev",
    "start": "bun run dev",
    "build": "astro check && astro build",
    "preview": "deno run -A npm:astro preview",
    "astro": "astro",
    "format": "prettier --write ./**/*.{ts,astro}"
  },
  "dependencies": {
    "@astrojs/check": "^0.7.0",
    "@astrojs/react": "^3.4.0",
    "@astrojs/tailwind": "^5.1.0",
    "@deno/astro-adapter": "github:denoland/deno-astro-adapter",
    "@radix-ui/react-slot": "^1.0.2",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "astro": "^4.9.2",
    "astro-seo": "^0.8.4",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "lucide-react": "^0.383.0",
    "prettier": "^3.3.0",
    "prettier-plugin-astro": "^0.14.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "tailwind-merge": "^2.3.0",
    "tailwindcss": "^3.4.3",
    "tailwindcss-animate": "^1.0.7",
    "typescript": "^5.4.5"
  },
  "prettier": {
    "tabWidth": 4,
    "useTabs": true,
    "singleQuote": false,
    "printWidth": 120,
    "bracketSameLine": false,
    "plugins": ["prettier-plugin-astro"],
    "overrides": [
      {
        "files": "*.astro",
        "options": {
          "parser": "astro"
        }
      }
    ]
  }
}
```

**Comment by EdamAme-x** [comment]
@kt3k do you have any idea?

**Comment by EdamAme-x** [comment]
> hmm... Errors no longer occur, but process.env is not loaded

so my code throwing error.

**Comment by EdamAme-x** [comment]
additional info: in develop mode

**Comment by irbull** [comment]
We now support Astro 5.0 with the adapter. I guess we can close this.
