### ISSUE TITLE
Release Notes Missing

### ISSUE THREAD

**Issue by und-miller** [denoland/deno-astro-adapter#32]
I've noticed that the CHANGELOG.md file has been removed in PR #29. Would it be possible to get release notes or a similar summary of changes for releases?

**Comment by irbull** [comment]
The changelog that was there was mostly about Astro itself, and not specific to the adapter. They came from when the Astro team maintained this. I'm not opposed to a changelog, but didn't notice it in any other Deno project -- not a good excuse not to have them, just my excuse :). But I think it would be good to use a common template / pattern across all the Deno projects related to Release Notes.

**Comment by und-miller** [comment]
Even creating a tagged release in GitHub with notes would be helpful. This would provide us with a clear understanding of the changes being pulled into our repositories.

**Comment by kt3k** [comment]
I created the release note pages (for versions from v0.1.1 to v0.1.5) https://github.com/denoland/deno-astro-adapter/releases

Do these work for you?

**Comment by irbull** [comment]
These look good to me. I can add a link in the README to this and then the link will appear in the overview at NPM.

**Comment by und-miller** [comment]
@kt3k looks amazing. Thank you!
